name: Deploy Frontend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy code
        uses: actions/checkout@v3

      - name: Upload FE lên host
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FE_FTP_HOST }}
          username: ${{ secrets.FE_FTP_USER }}
          password: ${{ secrets.FE_FTP_PASS }}
          local-dir: ./frontend/
          server-dir: /www.vanhuymnmth.somee.com/
